account/urls.py
from django.urls import path
from .views import *
from .import views

from django.contrib.auth import views as auth_views



app_name = 'account'


urlpatterns = [

    path('registration/',views.registration,name ='registration'),
    path('register/',views.registerPage,name ='register'),
   
    path('login/' ,views.loginPage , name='login'),
    path('admin_page/',views.adminPage ,name='admin_page'),
    path('update_info/', views.update_info, name="update_info"),
   
    path('logout/', views.logoutPage, name='logout'),
  
    path('client_register/',views.clientRegister,name ='client_register'),
    path('dashboard/',views.clientDashboard,name ='dashboard'),
  
    path('artisanPage/',views.artisanDashboard,name ='artisanPage'),
    
    
  

    
]

artisan/urls.py
from os import name
from django.urls import path
from .views import *
from .import views

from django.contrib.auth import views as auth_views



app_name = 'artisan'


urlpatterns = [
     path('artisanReg/', views.artisanRegistration, name='artisanReg'),
     path('confirmed_orders/', views.confirmedOrders, name='confirmed_orders'),
     path('artisan_update/', views.artisan_update, name="artisan_update"),

     path('paidJobs',views.paidJobs, name='paidJobs'),
     
     path('job_detail/<int:id>/',views.jobDetail, name='job_detail'),
     path('services_completed/',views.artisan_services, name='services_completed'),
     path('current_job/', views.currentJob, name='current_job'),
     path('accepted/<int:id>/', views.jobAccepted, name='accepted'),
     path('current_job_info/', views.CurrentJobInfo, name='current_job_info'),

     path('completed/<int:id>/', views.completeJob, name='completed'),
     path('congratulation/', views.congratulations, name='congratulation'),

      path("artisan-search/", SearchFlipView.as_view(), name="artisan-search"),
      path("outstanding/", views.outstandingPay, name="outstanding"),
     path("listJob/", views.JobList, name="listJob"),

      path('searchArtisans/<int:pk>/',views.artisanList,name="searchArtisans"),
      path("artisan_request/<int:pk>/", views.artisanRequest, name="artisan_request"),

       path("bank/", views.bankDetails, name="bank"),
     path("bank_update/", views.update_bank_info, name="bank_update"),
    



   
]

iwan_work/urls.py
from django.contrib import admin

from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' ,include('products.urls')),
    path('account/', include('account.urls')),
   
    path('artisan/' ,include('artisan.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import *
from .import views

app_name = 'products'


urlpatterns = [
    

    path('', views.home, name='home'),
    path('update_order/<int:pk>/',views.updateOrder,name='update_order'),
    path('detail/<int:id>/', views.details, name='detail'),
     path('jobs/' , AvailableJobs.as_view() ,name="jobs"),
    path('terms/',views.terms_and_conditions, name="terms"),
    
    path('product_dest/<pk>', views.product_dest, name='product_dest'),
    path('orderlist/', views.orderlist, name='orderlist'),
    path('add_to_cart/<pk>', views.add_to_cart, name='add_to_cart'),
    path('orderlist/', views.orderlist, name='orderlist'),
    path('add_item/<int:pk>', views.add_to_cart, name='add_item'),
    path('remove_item/<int:pk>', views.delete_order, name='remove_item'),

    path('search/', views.search , name='search'),
    path('contact/',views.contact ,name='contact'),
    
    path('payment/', views.payment, name='payment'),
     path('handle_confirmation/', views.handle, name='handle_confirmation'),
     path("post_service/", views.postServiceNeeded, name="post_service"),


    path('new/', views.newMethod, name='new'),
    path('add_service_item/<int:pk>', views.serviceRequestCart, name='add_service_item'), 
    path('servicelist/', views.Servicelist, name='servicelist'),
    path('service_payment/', views.servicePayment, name='service_payment'),

    path('payment_confirmation/', views.paymentConfirmation, name='payment_confirmation'),

    path("post_job/", views.PostJobItem, name="post_job"),

     path('service_list/', views.Servicelisting, name='service_list'),

    path('train_staff/', views.StaffTraining, name='train_staff'),
    
    path("workers_detail/", views.artisanDetail, name="workers_detail"),
    path("all_services/", views.serviceCompeleted, name="all_services"),
]

products/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets

from .models import *



class ProductForm(forms.ModelForm):
    
  
    class Meta:
        model = Product
        fields =('name','desc' ,'location')

    def __init__(self ,*args ,**kwargs):

        super(ProductForm ,self).__init__(*args ,**kwargs)
        self.fields['location'].empty_label ='select your zone'      



class OrderItemForm(forms.ModelForm):
     class Meta:
        model = OrderItem
        fields =('product','quantity','address' ,'description')




class  PostJobForm(forms.ModelForm):
    class Meta:
        model = PostJob
        fields =('services','number_of_people' ,'description','location','address')

    def __init__(self ,*args ,**kwargs):

        super(PostJobForm ,self).__init__(*args ,**kwargs)
        self.fields['location'].empty_label ='select location'

 

class  PostServiceForm(forms.ModelForm):
    class Meta:
        model = ServiceRequest
        fields =('product','number_of_workers','description','address','location')


    def __init__(self ,*args ,**kwargs):

        super(PostServiceForm ,self).__init__(*args ,**kwargs)
        self.fields['product'].empty_label ='Select services you want'



class  TrainingStaff(forms.ModelForm):
    class Meta:
        model = TrainStaff
        fields =('name','number_of_people','description','address','type_of_service','location')

    def __init__(self ,*args ,**kwargs):

        super(TrainingStaff ,self).__init__(*args ,**kwargs)
        self.fields['location'].empty_label ='Select location'
        

products/views.py
from django.shortcuts import render,redirect ,get_object_or_404
from django.contrib import auth, messages
from django.utils import timezone
from django.views.generic.base import TemplateView
from django.views.generic import (
    ListView 
)
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from account.models import Customer                
from .models import *
from django.db.models import Q 
from django.core.mail import send_mail
from django.conf import settings
from .forms import *



from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger




def home(request): 
    
    prod = Product.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(prod, 5)
    try:
        prod = paginator.page(page)
    except PageNotAnInteger:
        prod = paginator.page(1)
    except EmptyPage:
        prod = paginator.page(paginator.num_pages)

    return render(request,'homePage.html',{ 'prod': prod })



#list of jobs available
class AvailableJobs(TemplateView):
    template_name = 'services.html'  
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['service'] = Services.objects.all()
        context['prod'] =Product.objects.all()
        return context

    
#updating order
def updateOrder(request,pk):
    order = OrderItem.objects.get(pk=pk)
    form = OrderItemForm(instance = order)
    if request.method =="POST":
        form =OrderItemForm(request.POST,instance =order)
        if form.is_valid():
            form.save()
            message = "Successfully updated your item"
            return redirect('products:orderlist')
           
        else:
            message = "Not successful.Pls retry!"   

    context = {'form':form}

    return render(request,'products/update_order.html',context)         




def delete_order(request,pk):
    item = OrderItem.objects.get(pk=pk)
    item.delete()
    return redirect('products:orderlist')  



def details(request,id):
    home = Product.objects.get(id=id)
    context ={'home':home,}
             
    return render(request ,'detail.html',context )
 
    

def add_to_cart(request, pk):
    if request.user.is_authenticated:
        product = Product.objects.get(pk=pk)  
    
        order_item,created = OrderItem.objects.get_or_create(
            product =product,
            user = request.user,
            ordered = False,
            description = request.POST['description'],
       
            address = request.POST['address'],
            quantity = int(request.POST['quantity']),)

        order_qs = Order.objects.filter(user=request.user,ordered=False)
        
        if order_qs.exists():
            order =order_qs[0]
            if order.items.filter(product__pk=pk).exists():
                order_item.quantity +=1

                order_item.save()
                messages.info(request ,"Added additional worker successfully")
                return redirect("products:orderlist")

            else:
                order.items.add(order_item)
                messages.info(request ," successfully booked")
                return redirect("products:orderlist")  

        else:
            ordered_date =timezone.now()
            order =Order.objects.create(user=request.user, ordered_date=ordered_date)
            order.items.add(order_item)
            messages.info(request," Successfully booked")

            return redirect('products:orderlist')          
    
    else:
        messages.info(request,"Request unsuccessful! Please login before you can make a request")
        return render(request ,'account/service_request.html')   
        




def orderlist(request):
    if Order.objects.filter(user=request.user, ordered =False).exists():
        order = Order.objects.get(user=request.user, ordered=False)
        context={
            'order':order
        }
        return render(request, 'products/orderlist.html',context)

    return render(request ,'products/orderlist.html',{'message': "your cart is empty"})   




def products(request):
    prod = Product.objects.all()
    context ={
        'prod':prod
    }

    return render(request ,'products/items.html',context)
 




def product_dest(request, pk):
    prod = Product.objects.get(pk=pk)   
    context ={'prod':prod}
    return render(request ,'products/dest.html',context) 



def search(request):
    query = request.GET.get('search')
    item = Product.objects.filter(Q(name__icontains =query))

    context ={'item':item}
    if item:
        return render(request,'search.html',context)

    else:
        messages.warning(request,'Service not available at this time')
        return render(request,'search.html',context)
            


def contact(request):
    if request.method =='POST':
        message_name = request.POST['message-name']
        message_phone = request.POST.get("message-phone" ,False)
        message_email = request.POST['message-email']
        message  = request.POST['message']

        send_mail(
            message_name , # email subject
            message ,      # main message
            message_email , # from email 
            [settings.EMAIL_HOST_USER], # recipient, to email
        fail_silently=False)
        
        contacts = ContactUs()
        contacts.name =message_name
        contacts.phone = message_phone
        contacts.email = message_email
        contacts.message = message
        contacts.save()


        return render(request ,'contact.html',{'message_name' :message_name}) 

    else:
        return render(request ,'contact.html' ,{}) 



def payment(request):
    if Order.objects.filter(user=request.user, ordered =False).exists():

        order = Order.objects.get(user=request.user, ordered=False)
        context ={'order':order}
        return render(request, 'payments/payment.html',context) 

    return render(request ,'products/orderlist.html',{'message': "your cart is empty"})            




@csrf_exempt
def payment_confirmation(request):
 
    order = Order.objects.get(user=request.user, ordered=False)
    #get payment receipt from flutter wave
    payment_id =request.POST.get("tx_ref")
    
    order = Order.objects.get(user=request.user, payment_id=payment_id,ordered=False) 
    order.ordered = True
    order.save()
    if OrderItem.objects.filter(user=request.user, ordered=False,status='Pending'):
        OrderItem.objects.filter(user=request.user, ordered=False,status='Pending').update(ordered=True,status='Paid')

        if OrderItem.objects.filter(user=request.user, ordered=True,status='Paid'):
           
            return redirect('products:handle_confirmation')

        else:
            return render(request,'payments/no_order.html')    
       
        
    return redirect('products:home')

       
  
            
             

def handle_confirmation(request):
    if Order.objects.filter(user=request.user, ordered =True).exists():

        order_list = Order.objects.filter(user=request.user, ordered=True)   
        context ={'order_list':order_list}

        return render(request, 'payments/payment_confirmation.html',context) 
        
    return render(request ,'payments/no_order.html')             



def handle(request):

    list_items = ServiceOrder.objects.filter(user=request.user,ordered=True).order_by('-datetime_ofpayment')

    context ={'list_items':list_items}
    return render(request, 'payments/payment_details.html',context) 
   
        
    
    
  

def add_to_shop(request,pk):
    product = get_object_or_404(Product,pk=pk)

    order_item,created =OrderItem.objects.get_or_create(
        product=product,
       
    )

    order_qs = Order.objects.filter(user =request.user, ordered=False)

    if order_qs.exists():
        order =order_qs[0]

        if order.items.filter(product__pk=product.pk).exists():
            order_item.quantity +=1
            order_item.save()

            messages.info(request ,"Added additional worker successfully")
            return redirect("product:orderlist")


    else:
        ordered_date =timezone.now()
        order = Order.objects.create(user=request.user,ordered_date=ordered_date)
        order.items.add(order_item)

        messages.info(request," Successfully booked")
        return redirect('product:orderlist')



def terms_and_conditions(request):
    return render(request,'terms_and_conditions.html')   






class HomeView(ListView):
    model = Product
    template_name = 'new/home.html'

    def get_queryset(self, *args,**kwargs):
        qs= super(HomeView, self).get_queryset(*args, **kwargs)
        qs = qs.ordered_by('-date_added')


#new method


def newMethod(request):

    prod = Product.objects.all()
    address = OurLocations.objects.all()
    context ={
        'address':address,
        'prod':prod,
       
    }
    return render(request,'new/home.html',context)  





def serviceRequestCart(request, pk):
    if request.user.is_authenticated:

        artisan = Artisan.objects.get(pk=pk)  
        artisan_name = artisan.user.last_name
        job = artisan.profession_name 
        item = Product.objects.get(name=job)
    
        service_item,created = ServiceRequest.objects.get_or_create(
            artisan =Artisan.objects.get(pk=pk), #artisan,
            product =item,
            user = request.user,
            ordered = False,
            description = request.POST['description'],
            address = request.POST['address'],
            number_of_workers = int(request.POST['number_of_workers']),
           

        )
        order_qs = ServiceOrder.objects.filter(user=request.user,ordered=False)
        if order_qs.exists():
            order =order_qs[0]
            if order.items.filter(product__pk=pk).exists():
                service_item.number_of_workers +=1

                service_item.save()

templates/products/desc.html
{% extends 'main.html' %}
{% load static %}  

{% load crispy_forms_tags %}
{% block content %} 







{% if user.is_authenticated %}


<div class="container" style="margin-top: 70px;">
   
  <div class="row rn">
      <h2>{{ customer}}</h2>
    
      <div class="col-lg-4">
       
      <img class="thumbnail" src="{{ desc.image.url }}" alt="" width="500" height="333">
     
        <div class="box-element product">
          <br>
          <div >
            <h6><strong>{{ desc.name }}</strong></h6>
            <h6><strong>  <h4 style="display: inline-block; float: right;">
               {{ desc.price|floatformat:2 }}</h4></strong></h6> 

          <button data-product="{{desc.id}}" data-action
          ="add" class="btn btn-outline-secondary add-btn update-cart">Add to cart</button>
          <!--<a href="" class="btn btn-outline-success">view</a>-->
          <h4 style="display: inline-block; float: right;">
   </h4>
        </div>
      </div>
      </div>
     
    
    </div>
  

</div>








<div class="container" style="margin-top: 50px; align-items: right">
    <div class="row">

<h2>description products</h2>

        <div class="column">


<h1>{{desc.name}}</h1>
<h1>{{desc.desc}}</h1>
<h1>{{desc.category}}</h1>
<h1>{{desc.price}}</h1>

<img src="{{ desc.img.url }}" alt="">


<h2><a href="{% url 'products:add_to_cart' desc.pk %}">ADdd to cart</a></h2>

        </div>
       
    </div>
</div>


 


<div class="container" style="margin-top: 50px;">
    <div class="row row-cols-1 row-cols-md-4 g-4">
     
      <div class="col" style="height: 300px;">
        <h2 class="card-text">{{ desc.price }}</h2>
        <h2><a href="{% url 'products:add_to_cart' desc.pk %}" style="color: darkred;background: black;">Service Request </a></2>
        <div class="card">
          <img src="{{ desc.img.url }}" class="card-img-top" alt="..." style="height: 250px;">
          <div class="card-body">
            <h5 class="card-title">{{ desc.name}}</h5>
            <h5 class="card-title">{{ desc.location}}</h5>
            
            <p class="card-text">{{ desc.description }}</p>
          </div>
        </div>
      </div>
 
  </div>
 
</div>



</body>
</html>







 







{% endif %}


{% endblock %}

 

templates/products/job_detail.html
{% extends 'main.html' %}
{% load static %}  

{% block content %} 

 
<style>
  h3{
    text-align: center;
    font-size: 20px;
    font-family: 'Times New Roman', Times, serif;
    margin: 10px 0 30px 0;
    font-weight: 700;

  }
  @media(max-width:575px){
    .artisan-job-info{
      margin: 30px;
    }
  }
  @media(max-width:300px){
    .artisan-job-info{
      margin: 10px;
    }
  }
  </style>


     
      <div class="row artisan-job-info" style="margin-top: 40px;">
     
        <div class="col-md-12">
          <h3>Job Details</h3>
          <div class="card card-body">

     <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="card-item">
           
            <h5>Job Title : {{ job_info.product.name }}</h5>
            <p>Posted By: {{ job_info.user }} </p>
            <h6>Location: {{ job_info.location }}</h6>
            <h6>Date Posted: {{job_info.date_created}}</h6>
          </div>
          <div class="card-detail">
            <h6>Amount: {{ job_info.get_service_rate }}</h6>
            
            <p>{{ job_info.product.address }}</p>
            <p>Number of worker: {{ job_info.number_of_workers }}</p>
          </div>
            <div class="card-body">
              <h5>Job description</h5>
              <p>{{ job_info.description }}</p>
            </div>
          </div>
        </div>

       <div class="col-md-4">
        <a class="btn btn-success"  href="{% url 'artisan:accepted' job_info.id %}">Apply Now</a>
        <!--<a class="btn btn-danger" href="{% url 'artisan:confirmed_orders' %}">Decline</a>-->
       </div>
      </div>
     </div>
          </div>
        </div>
      
      

    

{% endblock %}

templates/products/orderlist.html
{% extends 'main.html' %}
{% load static %}  

{% block content %} 





{% if user %}
<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<h5>Customer:</h5>
			<hr>
			<a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'account:update_info' %}">Update Your information</a>
			<a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'products:jobs' %}">Place Order</a>

		</div>
	</div>


	<div class="col-md">
		<div class="card card-body">
			<h5>Contact Information</h5>
			<hr>
			<p>username: {{user.username}}</p>
			<p>first name: {{user.first_name}}</p>
			<p>Phone: {{user.details.phone}}</p>
		
			<p>Email: {{user.email}}</p>
		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Total Orders</h5>
			<hr>
			<h1 style="text-align: center;padding: 10px">{{ order.get_total_count }}</h1>
		</div>
	</div>


{% endif %}




<br><br>
{%  include 'status.html' %}
<link rel="stylesheet" href="{% static 'css/cs.css' %}" >

<br>








<br>


   





<div class="row">
	<div class="col-md-5">
		
	<br>
	<br>
		<div class="card card-body">
			<!--<td colspan="4"><a href="{% url 'products:handle_confirmation' %}" class="btn btn-danger" style="color: whitesmoke; float: right; font-size: 25px;">View paid services</a>-->
			<a class="btn btn-primary  btn-sm btn-block" style="color: whitesmoke; float: right; font-size: 20px;" href="{% url 'products:handle_confirmation' %}">Your previous  Paid Services</a>
			<table class="table table-sm">
				<tr>

					
					<th></th>
					
					
				</tr>

				<!--{% for customer in customers %}
					<tr>
						<td><a class="btn btn-sm btn-info" href="">View</a></td>
						<td>{{user.username}}</td>
						<td>{{customer.phone}}</td>
					</tr>
				
				{% endfor %}-->

			</table>
		</div>
	</div>
	<!--<td><b>{{ object.get_total_count }}</b></td>-->

	<div class="col-md-7">
		
		<h5>YOUR LASTEST  ORDERS</h5>
		<hr>
		<div class="card card-body">
			<a class="btn btn-primary  btn-sm btn-block" href="{% url 'products:jobs' %}">Create Order</a>
			
			<table class="table table-sm" style="margin-top: 30px;">
				<tr>
					<th>No</th>
					<th>Product</th>
					<th>Price</th>
					
                    <th>No of workers </th>
					<th>Total Amount </th>
					<th>Paid</th>
                    <th>Date Orderd</th>
					<!--<th>Final Amount </th>-->
				</tr>

                {% for order_item in order.items.all %}
                <tr>
					<td>{{ forloop.counter }}</td>
					<td>{{ order_item.product.name }}</td>
                    <td>{{ order_item.product.price }}</td>
					<td style="text-align: center;">
						<!--<p><strong><i class="fas fa-arrow-up"></i></strong></p>
								<img data-product="{{ item.product.id }}" data-action="add" class="chg-quantity update-cart" src="{% static 'images/arrow-up.png' %}" alt="" style="background-color: green; font-size: x-large;">-->
								
							<!--<img data-product="{{ item.product.id }}" data-action="remove" class="chg-quantity update-cart" class="chg-quantity" src="{% static 'images/arrow-down.png' %}" alt="" style="background-color: green;">
							<i class="fas fa-sort"></i>-->
		

						<!--<strong><a href="{% url 'products:add_item' order_item.pk %}"><i class="fas fa-sort-up"></i></a></strong>-->
						{{ order_item.quantity }}

					
					</td>		
					
					<td>{{order_item.get_total_item_price}}</td>
					<td>{{order_item.ordered}}</td>

					<td>{{order_item.date_created}}</td>
				

					<!--<td>{{order_item.get_final_price}}</td>
					<td style="color: tomato;">{{order_item.id}}</td>
					<td style="color: blue;">{{order_item.pk}}</td>-->
		
					
					<td><a class="btn btn-sm btn-info" style="padding: 4px;" href="{% url 'products:update_order' order_item.id %}">Update</a></td>

					<td><a class="btn btn-sm btn-danger" style="padding: 4px;" href="{% url 'products:remove_item' order_item.id %}">Delete</a></td>
				</tr>
		{% endfor %}

		
		
		
		
		<!--<tr style="margin-top: 40px; padding: 40px;">
			<td style="margin-bottom: 40px;"></td>
			
			   <td colspan="3" ><b>VAT </b></td>
			   <td><b>100</b></td>
			   <td><b>{{ order.get_vat }}</b></td>
			    
		   </tr>-->
		   {% if order.get_total_price  %}
		   <tr  style="background-color: black; padding: 30px;">
			<td></td>
	   
			   <td colspan="3" ><b style="color: whitesmoke;"> Amount Before Tax /Amount payable</b></td>
			   <td style="color: whitesmoke;"><b>{{ order.get_total_price }}</b></td>
			   <td colspan="4"><a href="{% url 'products:payment' %}" class="btn btn-danger" style="color: whitesmoke; float: right;"> Pay Now</a>
		   
			   
		   
		   </tr>
		   {% endif %}
		<!--<tr  style="background-color: black; padding: 30px;">
			<td></td>
	   
			   <td colspan="3" ><b style="color: whitesmoke;">Total Payable Amount </b></td>
			   <td style="color: whitesmoke;"><b>{{ order.get_final_amount }}</b></td>
			   <td colspan="4"><a href="" class="btn btn-danger" style="color: whitesmoke; float: right;"> Pay</a>
		   
		   </tr>-->
	
			</table>
			
		
		</div>
			
		</div>
		
	</div>
</div>




{% endblock %}

templates/products/servicelist.html
{% extends 'main.html' %}
{% load static %}  

{% block content %} 





{% if user %}
<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<h5>Customer:</h5>
			<hr>
			<a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'account:update_info' %}">Update Your information</a>
			<a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'products:jobs' %}">Place Order</a>

		</div>
	</div>


	<div class="col-md">
		<div class="card card-body">
			<h5>Contact Information</h5>
			<hr>
			<p>username: {{user.username}}</p>
			<p>first name: {{user.first_name}}</p>
			<p>Phone: {{user.details.phone}}</p>
		
			<p>Email: {{user.email}}</p>
		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Total Orders</h5>
			<hr>
			<h1 style="text-align: center;padding: 10px">{{ order.get_total_count }}</h1>
		</div>
	</div>


{% endif %}




<br><br>
{%  include 'status.html' %}
<link rel="stylesheet" href="{% static 'css/cs.css' %}" >

<br>








<br>


   





<div class="row">
	<div class="col-md-5">
		
	<br>
	<br>
		<div class="card card-body">
			<!--<td colspan="4"><a href="{% url 'products:handle_confirmation' %}" class="btn btn-danger" style="color: whitesmoke; float: right; font-size: 25px;">View paid services</a>-->
			<a class="btn btn-primary  btn-sm btn-block" style="color: whitesmoke; float: right; font-size: 20px;" href="{% url 'products:handle_confirmation' %}">Your previous  Paid Services</a>
			<table class="table table-sm">
				<tr>
					<th></th>
					
					
				</tr>


			</table>
		</div>
	</div>


	<div class="col-md-7">
		
		<h5>YOUR LASTEST  ORDERS</h5>
		<hr>
		<div class="card card-body">
			<a class="btn btn-primary  btn-sm btn-block" href="{% url 'products:jobs' %}">Create Order</a>
			
			<table class="table table-sm" style="margin-top: 30px;">
				<tr>
					<th>No</th>
					<th>Product</th>
					<th>Price</th>
					
                    <th>No of workers </th>
					<th>Total Amount </th>
					<th>Paid</th>
                    <th>Date Orderd</th>
					<!--<th>Final Amount </th>-->
				</tr>

                {% for order_item in order.items.all %}
                <tr>
					<td>{{ forloop.counter }}</td>
					<td>{{ order_item.product.name }}</td>
                    <td>{{ order_item.product.price }}</td>
					<td style="text-align: center;">
							{{ order_item.quantity }}

					
					</td>		
					
					<td>{{order_item.get_total_item_price}}</td>
					<td>{{order_item.ordered}}</td>

					<td>{{order_item.date_created}}</td>
				

					
					<td><a class="btn btn-sm btn-info" style="padding: 4px;" href="{% url 'products:update_order' order_item.id %}">Update</a></td>

					<td><a class="btn btn-sm btn-danger" style="padding: 4px;" href="{% url 'products:remove_item' order_item.id %}">Delete</a></td>
				</tr>
		{% endfor %}

		
		
		
		   {% if order.get_total_price  %}
		   <tr  style="background-color: black; padding: 30px;">
			<td></td>
	   
			   <td colspan="3" ><b style="color: whitesmoke;"> Amount Before Tax /Amount payable</b></td>
			   <td style="color: whitesmoke;"><b>{{ order.get_total_price }}</b></td>
			   <td colspan="4"><a href="{% url 'products:service_payment' %}" class="btn btn-danger" style="color: whitesmoke; float: right;"> Pay Now</a>
		   
			   
		   
		   </tr>
		   {% endif %}
		
			</table>
			
		
		</div>
			
		</div>
		
	</div>
</div>




{% endblock %}