account/urls.py
from django.urls import path
from .views import *
from .import views

from django.contrib.auth import views as auth_views



app_name = 'account'


urlpatterns = [

    path('registration/',views.registration,name ='registration'),
    path('register/',views.registerPage,name ='register'),
   
    path('login/' ,views.loginPage , name='login'),
    path('admin_page/',views.adminPage ,name='admin_page'),
    path('update_info/', views.update_info, name="update_info"),
   
    path('logout/', views.logoutPage, name='logout'),
  
    path('client_register/',views.clientRegister,name ='client_register'),
    path('dashboard/',views.clientDashboard,name ='dashboard'),
  
    path('artisanPage/',views.artisanDashboard,name ='artisanPage'),
    
    
  

    
]

iwan_work/urls.py
from django.contrib import admin

from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' ,include('products.urls')),
    path('account/', include('account.urls')),
   
    path('artisan/' ,include('artisan.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import *
from .import views

app_name = 'products'


urlpatterns = [
    

    path('', views.home, name='home'),
    path('update_order/<int:pk>/',views.updateOrder,name='update_order'),
    path('detail/<int:id>/', views.details, name='detail'),
     path('jobs/' , AvailableJobs.as_view() ,name="jobs"),
    path('terms/',views.terms_and_conditions, name="terms"),
    
    path('product_dest/<pk>', views.product_dest, name='product_dest'),
    path('orderlist/', views.orderlist, name='orderlist'),
    path('add_to_cart/<pk>', views.add_to_cart, name='add_to_cart'),
    path('orderlist/', views.orderlist, name='orderlist'),
    path('add_item/<int:pk>', views.add_to_cart, name='add_item'),
    path('remove_item/<int:pk>', views.delete_order, name='remove_item'),

    path('search/', views.search , name='search'),
    path('contact/',views.contact ,name='contact'),
    
    path('payment/', views.payment, name='payment'),
     path('handle_confirmation/', views.handle, name='handle_confirmation'),
     path("post_service/", views.postServiceNeeded, name="post_service"),


    path('new/', views.newMethod, name='new'),
    path('add_service_item/<int:pk>', views.serviceRequestCart, name='add_service_item'), 
    path('servicelist/', views.Servicelist, name='servicelist'),
    path('service_payment/', views.servicePayment, name='service_payment'),

    path('payment_confirmation/', views.paymentConfirmation, name='payment_confirmation'),

    path("post_job/", views.PostJobItem, name="post_job"),

     path('service_list/', views.Servicelisting, name='service_list'),

    path('train_staff/', views.StaffTraining, name='train_staff'),
    
    path("workers_detail/", views.artisanDetail, name="workers_detail"),
    path("all_services/", views.serviceCompeleted, name="all_services"),
]

templates/dashboard/client/artisan_info.html
{% extends 'dashboard/client/dashboard_links.html' %}

{% block content %}

<style>

  .container-fluid{
    display: none;
  }
    .row{
        margin-top: 70px;
    }
    h3{
        text-align: center;
        margin-left: 20px;
        font-size: 18px;
        font-weight: 800;
    }
    td img{
        width: 150px !important;
        height: 130px !important;
        margin-left: 40px;

    }
    .card-img{
    width: 100px;
    height: 100px;
    
}
.card-img img{
    border-radius: 50%;
    width: 100%;
    height: 100%;
   
}
@media (max-width:950px) {
    .container-fluid{
        display: block;
    }
    .container-scroller {
    overflow: hidden;
    height: 100px;
}
    
}
    @media (max-width:650px) {
  td img {
    width: 75px !important;
    height: 75px !important;
  }.table th, .table td {
    padding: 2px;
    vertical-align: top;
    border-top: 1px solid #f3f3f3;
}
.table td {
    font-size: 14px !important;
}
    }
@media (max-width:500px) {
    .table thead th {
    border-top: 0;
    border-bottom-width: 1px;
    font-weight: 500;
    font-size: 14px !important;
}
.project-orders-table thead tr th:first-child {
    padding-left: 0.3rem;
    padding-right: 0.5rem;
}
}
@media (max-width:400px) {
    .table thead th {
    border-top: 0;
    border-bottom-width: 1px;
    font-weight: 500;
    font-size: 12px !important;
}
    
}
    



</style>
<div class="row">
    <h3>Artisan's information</h3>
     <br>
    {% for order_item in artisans %}

     <div class="card-img mt-2">
    <img src="{{ order_item.artisan.profile_img.url }}" alt="">
     </div>
    {% endfor %}
    
    <div class="col-md-12">
      <div class="card">
       
        <div class="table-responsive pt-3">
          <table class="table table-striped project-orders-table">
            <thead>
              <tr>
                <!--<th class="ml-5">ID</th>-->
                
                <th>Work Type</th>
               
                <th>Full Name</th>
                <th>Phone</th>
              
                <th>Date</th>
            
              </tr>
            </thead>
            <tbody>

              
              
              {% for order_item in artisans %}
              <tr>
               

                <td>{{ order_item.product.name }}</td>
                <td>{{ order_item.artisan.user.first_name }} &nbsp;{{ order_item.artisan.user.last_name }}</td>
             
                <td>{{ order_item.artisan.phone }} </td>
           
                <td>{{order_item.date_created}}</td>

                

                
              </tr> 
           
              {% endfor %}
            </tbody>
       
          </table>
        </div>
      </div>
    </div>
  </div>


  {% endblock %}

templates/dashboard/client/clientDetail.html
{% extends 'main.html' %}
{% load static %}  
{% block content %} 

{% load crispy_forms_tags %} 



{% include 'dashboard/client/index.html'%}
{% endblock %}

templates/dashboard/client/completed_services.html
{% extends 'dashboard/client/dashboard_links.html' %}
{% load static %}


{% block content %}




  <link rel="stylesheet" href="{% static 'template/css/vertical-layout-light/style.css' %}">


   
<style>
    .container-fluid{
     display: none;
   }
   @media (max-width:950px) {
    .container-fluid{
        display: block;
    }
    .container-scroller {
    overflow: hidden;
    height: 100px;
}
}
</style> 



<div class="container">

<div class="row">
    <div class="col-md-12">
        <div class="card">
        <div class="table-responsive pt-3">
           <h3>Transactions Details</h3>
            <table class="table table-striped project-orders-table">
            <thead>
            
            <tr>
                <th>ID</th>
                <th>Service requested</th>
                <th>Artisan's Nmae </th>
                <th>No of workers </th>
              
                <th>Paid</th>
                <th>Address </th>
                <th>Job Location </th>
                <th>Date paid</th>
                <th>Accepted date </th>
                <th>Compeleted? </th>
                <th>Unity price </th>
                <th>Amount </th>
               
              
            </tr>
            </thead>
    
            <tbody>
                
                    
        {% for item in all_jobs  %}
             
                <tr>
                    <td>#{{ forloop.counter }}</td>
                <td>{{item.product.name }}</td>
               
                <td>{{item.user.last_name}}</td>
                <td>{{item.number_of_workers}}</td>
                <td>{{item.ordered}}</td>
                <td>{{item.address}}</td>
                <th>{{item.location}} </th>
                <td >{{item.date_created}}</td>
                <td> {{item.accepted_date}}</td>
                <td> {{ item.work_done}}</td>
                <td> {{item.product.price}}</td>
                <td>{{item.get_total_item_price}}</td>
            
                </tr>
       
        {% endfor %}  
            </tbody>
                
           </table>
        </div>
        </div>
    </div>
    </div>
</div>




    


{% endblock %}

  

templates/dashboard/client/dashboard_links.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Client Dashboard</title>
  <!-- base:css -->
  <link rel="stylesheet" href="{% static 'template/vendors/typicons/typicons.css' %}">
  <link rel="stylesheet" href="{% static 'template/vendors/css/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'template/css/vertical-layout-light/style.css' %}">
  <!-- endinject -->
  <!--<link rel="shortcut icon" href="{% static 'template/images/favicon.png' %}" />-->
  <link rel="shortcut icon" href="{% static 'images/brand/title_image2.png' %}" />

</head>



<style>
  li a{
    list-style: none;
  
    list-style: lower-alpha;
  }
 
</style>
<body>
  

    <!-- partial:partials/_navbar.html -->
  <div class="container-scroller">
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="navbar-brand-wrapper d-flex justify-content-center">
        <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
          <a class="navbar-brand brand-logo" href="index.html"><img src="{%  static 'images/brand2.jpg' %}" alt="logo"/></a>
          <a class="navbar-brand brand-logo-mini" href="index.html"><img src="images/logo-mini.svg" alt="logo"/></a>
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="typcn typcn-th-menu"></span>
          </button>
        </div>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
       
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="typcn typcn-th-menu"></span>
        </button>
      </div>
    </nav>
  

      
   

 
        
      
    <!-- partial -->
    <nav class="navbar-breadcrumb col-xl-12 col-12 d-flex flex-row p-0">
      <div class="navbar-links-wrapper d-flex align-items-stretch">
        <div class="nav-link">
          <a href="{% url 'products:home' %}">Home</a><!--<i class="typcn typcn-calendar-outline"></i></a>-->
        </div>
        <div class="nav-link">
          <a href="{% url 'account:dashboard' %}">Dashboard<!--<i class="typcn typcn-document-text"></i>--></a>
        </div>
        <div class="nav-link">
          <a href="% url 'account:logout' %}">Logout<!--<i class="typcn typcn-document-text"></i>--></a>
        </div>
      </div>
      
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <ul class="navbar-nav mr-lg-2">
        
          <li class="nav-item">
           
            <h4 class="mb-0">Welcome,{{ request.user}}</h4>
          </li>
        </ul>
    
      </div>
    </nav>
    <div class="container-fluid page-body-wrapper">
   
      <!-- partial:partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <!--<li class="nav-item">
            <a class="nav-link" href="index.html">
              <i class="typcn typcn-device-desktop menu-icon"></i>
              <span class="menu-title">Dashboard</span>
              <div class="badge badge-danger">new</div>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
              <i class="typcn typcn-document-text menu-icon"></i>
              <span class="menu-title"><b>Services</b></span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-basic">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="{% url 'products:servicelist' %}"><b>Unpaid Services</b> </a></li>
                <li class="nav-item"> <a class="nav-link" href="#"><b>Artisan's Detail</b></a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'products:handle_confirmation' %}"><b>Previous Transactions</b></a></li>
                 <li class="nav-item"> <a class="nav-link" href="pages/ui-features/typography.html"><b>All jobs done</b></a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'account:update_info' %}"><b>Edit Your information</b></a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'products:home' %}"><b>Place Order</b></a></li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#form-elements" aria-expanded="false" aria-controls="form-elements">
              <i class="typcn typcn-film menu-icon"></i>
              <span class="menu-title"><b>Account Setting</b></span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="form-elements">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"><a class="nav-link" href="{% url 'account:update_info' %}"><b>Edit Your information</b></a></li>

            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'products:home' %}">
              <i class="typcn typcn-mortar-board menu-icon"></i>
              <span class="menu-title"><b>Place Order</b></span>
            </a>
          </li>-->

          <li class="nav-item nav-link-items">
            <div class="nav-link">
              <a href="{% url 'account:dashboard' %}" class="btn btn-success">Dashboard</a><!--<i class="typcn typcn-calendar-outline"></i></a>-->
            </div>
            <div class="nav-link">
              <a href="{% url 'products:home' %}" class="btn btn-dark">Home</a><!--<i class="typcn typcn-calendar-outline"></i></a>-->
            </div>
            <div class="nav-link">
              <a href="% url 'account:logout' %}" class="btn btn-danger">Logout<!--<i class="typcn typcn-document-text"></i>--></a>
            </div>
          </li>
         
         
        </ul>
      </nav>
      
   
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
 
{% block content %}


{% endblock %}


  {% include 'footer.html' %}

  <!-- base:js -->
  <script src="{% static 'template/vendors/js/vendor.bundle.base.js ' %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page-->
  <script src="{% static 'template/vendors/chart.js/Chart.min.js ' %}"></script>
  <!-- End plugin js for this page-->
  <!-- inject:js -->
  <script src="{% static 'template/js/off-canvas.js ' %}"></script>
  <script src="{% static 'template/js/hoverable-collapse.js ' %}"></script>
  <script src="{% static 'template/js/template.js ' %}"></script>
  <script src="{% static 'template/js/settings.js ' %}"></script>
  <script src="{% static 'template/js/todolist.js ' %}"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="{% static 'template/js/dashboard.js ' %}"></script>
  <!-- End custom js for this page-->
</body>

</html>