account/urls.py
from django.urls import path
from .views import *
from .import views

from django.contrib.auth import views as auth_views



app_name = 'account'


urlpatterns = [

    path('registration/',views.registration,name ='registration'),
    path('register/',views.registerPage,name ='register'),
   
    path('login/' ,views.loginPage , name='login'),
    path('admin_page/',views.adminPage ,name='admin_page'),
    path('update_info/', views.update_info, name="update_info"),
   
    path('logout/', views.logoutPage, name='logout'),
  
    path('client_register/',views.clientRegister,name ='client_register'),
    path('dashboard/',views.clientDashboard,name ='dashboard'),
  
    path('artisanPage/',views.artisanDashboard,name ='artisanPage'),
    
    
  

    
]

artisan/urls.py
from os import name
from django.urls import path
from .views import *
from .import views

from django.contrib.auth import views as auth_views



app_name = 'artisan'


urlpatterns = [
     path('artisanReg/', views.artisanRegistration, name='artisanReg'),
     path('confirmed_orders/', views.confirmedOrders, name='confirmed_orders'),
     path('artisan_update/', views.artisan_update, name="artisan_update"),

     path('paidJobs',views.paidJobs, name='paidJobs'),
     
     path('job_detail/<int:id>/',views.jobDetail, name='job_detail'),
     path('services_completed/',views.artisan_services, name='services_completed'),
     path('current_job/', views.currentJob, name='current_job'),
     path('accepted/<int:id>/', views.jobAccepted, name='accepted'),
     path('current_job_info/', views.CurrentJobInfo, name='current_job_info'),

     path('completed/<int:id>/', views.completeJob, name='completed'),
     path('congratulation/', views.congratulations, name='congratulation'),

      path("artisan-search/", SearchFlipView.as_view(), name="artisan-search"),
      path("outstanding/", views.outstandingPay, name="outstanding"),
     path("listJob/", views.JobList, name="listJob"),

      path('searchArtisans/<int:pk>/',views.artisanList,name="searchArtisans"),
      path("artisan_request/<int:pk>/", views.artisanRequest, name="artisan_request"),

       path("bank/", views.bankDetails, name="bank"),
     path("bank_update/", views.update_bank_info, name="bank_update"),
    



   
]

iwan_work/urls.py
from django.contrib import admin

from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' ,include('products.urls')),
    path('account/', include('account.urls')),
   
    path('artisan/' ,include('artisan.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import *
from .import views

app_name = 'products'


urlpatterns = [
    

    path('', views.home, name='home'),
    path('update_order/<int:pk>/',views.updateOrder,name='update_order'),
    path('detail/<int:id>/', views.details, name='detail'),
     path('jobs/' , AvailableJobs.as_view() ,name="jobs"),
    path('terms/',views.terms_and_conditions, name="terms"),
    
    path('product_dest/<pk>', views.product_dest, name='product_dest'),
    path('orderlist/', views.orderlist, name='orderlist'),
    path('add_to_cart/<pk>', views.add_to_cart, name='add_to_cart'),
    path('orderlist/', views.orderlist, name='orderlist'),
    path('add_item/<int:pk>', views.add_to_cart, name='add_item'),
    path('remove_item/<int:pk>', views.delete_order, name='remove_item'),

    path('search/', views.search , name='search'),
    path('contact/',views.contact ,name='contact'),
    
    path('payment/', views.payment, name='payment'),
     path('handle_confirmation/', views.handle, name='handle_confirmation'),
     path("post_service/", views.postServiceNeeded, name="post_service"),


    path('new/', views.newMethod, name='new'),
    path('add_service_item/<int:pk>', views.serviceRequestCart, name='add_service_item'), 
    path('servicelist/', views.Servicelist, name='servicelist'),
    path('service_payment/', views.servicePayment, name='service_payment'),

    path('payment_confirmation/', views.paymentConfirmation, name='payment_confirmation'),

    path("post_job/", views.PostJobItem, name="post_job"),

     path('service_list/', views.Servicelisting, name='service_list'),

    path('train_staff/', views.StaffTraining, name='train_staff'),
    
    path("workers_detail/", views.artisanDetail, name="workers_detail"),
    path("all_services/", views.serviceCompeleted, name="all_services"),
]

templates/available_order.html
    {% extends 'main.html' %}
    {% load static %}  
    
    {% block content %} 

<div class="container">
  <h3> here will be for list of confirmed  jobs</h3>
</div>


 <button type="button" class="btn btn-primary position-relative">
      Inbox
      <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
        99+
        <span class="visually-hidden">unread messages</span>
      </span>
    </button>


    <button type="button" class="btn btn-primary position-relative">
      Profile
      <span class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle">
        <span class="visually-hidden">New alerts</span>
      </span>
    </button>





    
    
    
    
    
    {% if user %}
    <div class="row">
      <div class="col-md">
        <div class="card card-body">
          <h5>Customer:</h5>
          <hr>
          <a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'artisan:artisan_update' %}">Update Your information</a>

        </div>
      </div>
    
    
      <div class="col-md">
        <div class="card card-body">
          <h5>Contact Information</h5>
          <hr>
          <p>username: {{user.username}}</p>
          <p>first name: {{user.first_name}}</p>
          <p>Phone: {{user.artisan.phone}}</p>
          <p>NIN: {{user.artisan.nin}}</p>
         
          <p>Email: {{user.email}}</p>
          <p>Address: {{user.artisan.address}}</p>
        </div>
      </div>
    
      <div class="col-md">
        <div class="card card-body">
          <h5>Total Orders</h5>
          <hr>
          <h1 style="text-align: center;padding: 10px">{{ order.get_total_count }}</h1>
        </div>
      </div>
    
    
    {% endif %}
    
    
    
    
    <br><br>
    {%  include 'status.html' %}
    <link rel="stylesheet" href="{% static 'css/cs.css' %}" >
    
    <br>
    
    
    
    
    
    
    
    
    
    <div class="row">
      <div class="col-md-5">
        <h5>CUSTOMERS:</h5>
        <hr>
        <div class="card card-body">
          <a class="btn btn-danger  btn-sm btn-block" href="{% url 'artisan:paidJobs' %}">Available jobs in your area</a>
          <table class="table table-sm">
            <tr>
              <th></th>
              
              
            </tr>
    
            {% for customer in customers %}
              <tr>
                <td><a class="btn btn-sm btn-info" href="">View</a></td>
                <td>{{user.username}}</td>
                <td>{{customer.phone}}</td>
              </tr>
            {% endfor %}
    
          </table>
        </div>
      </div>
      <!--<td><b>{{ object.get_total_count }}</b></td>-->
      <div class="col-md-7">
        
        <h5>YOUR LASTEST  ORDERS</h5>
        <hr>
        <div class="card card-body">
          <a class="btn btn-primary  btn-sm btn-block" href="">Service Completed </a>
          
          <table class="table table-sm" style="margin-top: 30px;">
            <tr>
              <th>No</th>
              <th>Service</th>
              <th>Address</th>
              <th>Date </th>
              <th>Price</th>
              
                        
            </tr>
    
                    {% for order_item in order.items.all %}
                    <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ order_item.product.name }}</td>
                        <td>{{ order_item.product.price }}</td>
              <td style="text-align: center;">
               
                {{ order_item.quantity }}
    
              
              </td>		
              
              <td>{{order_item.get_total_item_price}}</td>
              <td>{{order_item.ordered}}</td>
    
              <td>{{order_item.date_created}}</td>
            
        
              
              <td><a class="btn btn-sm btn-info" style="padding: 4px;" href="{% url 'products:update_order' order_item.id %}">Update</a></td>
    
              <td><a class="btn btn-sm btn-danger" style="padding: 4px;" href="{% url 'products:remove_item' order_item.id %}">Delete</a></td>
            </tr>
        {% endfor %}
    
        
        
      
           <tr  style="background-color: black; padding: 30px;">
          <td></td>
         
             <td colspan="3" ><b style="color: whitesmoke;">Total Amount  </b></td>
             <td style="color: whitesmoke;"><b>{{ order.get_total_price }}</b></td>
  
      
           </tr>
  
      
          </table>
          
        
        </div>
          
        </div>
        
      </div>
    </div>
    
    
    
    
    {% endblock %}    

templates/check.html
{% extends 'main.html'%}
{% load static %}
{% block content %}

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>I_client_dashboard</title>
 
  <link rel="stylesheet" href="{% static 'template/css/vertical-layout-light/style.css' %}">
  <!-- endinject -->


</head>



 <style>
  .roww{
  width: 100%;
  height: 150px;
  border: 1px solid #ccc;
  border-radius: 5px;
  padding: 10px;
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
  margin: 20px;
  }
  .col-md-3{
    margin-top: 30px;
  }
  .text-uppercase{
    text-align: center;
    margin-bottom: 50px !important;
  }
 </style>  

  <h6 class="mb-2 mb-md-0 text-uppercase font-weight-medium">Available jobs</h6>
 <div class="content-wrapper">  
  {% if areaJobs %}  
<div class="container">
  {% for item in areaJobs %}
  <div class="row roww">
    <div class="col-md-9">
      <h4>{{ item.product.name }}</h4>
      <p>{{ item.description }}</p>
      <p>Posted by :{{ item.user }}</p>
      <p>Posted on :{{ item.date_created }}</p>

    </div>
    <div class="col-md-3">
      <a href="{% url 'artisan:job_detail' item.id %}" class="btn btn-dark">View Details</a>
    </div>
  </div>
  {% endfor %}
</div>
{% elif price %}

<div class="card">
  <div class="card-body border-bottom">
    <div class="d-flex justify-content-between align-items-center flex-wrap">
      <h6 class="mb-2 mb-md-0 text-uppercase font-weight-medium">Outstanding Payment</h6>
    </div>
      <div class="col-md-7" style="align-items: center;">
       
              <div class="card card-body">
              <table class="table table-sm" >
              <tr style="margin-top: 70px;"> 
              <h3 style="text-transform: capitalize;">{{ price }}</h3>

              <hr>
             
              </tr>
              </table>
              </div>
            </div>
          </div>
</div>

{% elif no_job %}
<div class="card">
  <div class="card-body border-bottom">
    <div class="d-flex justify-content-between align-items-center flex-wrap">
      <h6 class="mb-2 mb-md-0 text-uppercase font-weight-medium">Number Of Jobs Done</h6>
    </div>
      <div class="col-md-7" style="align-items: center;">
       
              <div class="card card-body">
              <table class="table table-sm" >
              <tr style="margin-top: 70px;"> 
              <h3 style="text-transform: capitalize;">{{ no_job }}</h3>

              <hr>
             
              </tr>
              </table>
              </div>
            </div>
          </div>
       </div>
    
       {% endif %}
 </div>

{% endblock %}

templates/contact.html
{% extends 'main.html' %}
{% load static %}  
{% block content %} 

{% load crispy_forms_tags %} 

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<style>

/* contact us*/

</style>


<section class="contact">
    
	<div class="content">
		<h2>Contact Us</h2>
		<p>Contact us for all your household jobs and professional services</p>
	</div>
	<div class="container">
		<div class="contactInfo">
			<div class="box">
				<div class="icon">
                    <i class="far fa-address-card"></i>
                </div>
				<div class="text">
					<h3>Address</h3>
					<p>Here will be for office address</p>
				</div>
			</div>
			<div class="box">
				<div class="icon">
                    <i class="fas fa-phone-square-alt"></i>
                </div>
				<div class="text">
					<h3>Phone</h3>
					<p>+2348079385255 </p>
					<p> +2348177206739</p>
				</div>
                
			</div>
			<div class="box">
				<div class="icon">
                    <i class="fas fa-envelope-square"></i>
                </div>
				<div class="text">
					<h3>Email</h3>
					<p>icanwork51@gmail.com</p>
				</div>
			</div>
		
		</div>
        <div class="contactForm">
            <form action="{% url 'products:contact' %}" method="POST">
                <h2>Send Us A  Message  - {{ message_name }}</h2>
                {% csrf_token %}
                <div class="inputBox">
                    <input type="text" name="message-name" placeholder="Full name" required>
                    <!--<span>Full Name</span>-->
                </div>
                <div class="inputBox">
                    <input type="text" name="message-phone" placeholder="Phone Number" required>
                   <!--- <span>Phone</span>-->
                </div>
                <div class="inputBox">
                    <input type="text" name="message-email" placeholder="Email" required>
                    <!--<span>Email</span>-->
                </div>
                <div class="inputBox">
                    <textarea name="message" placeholder="Type your message here" id="" cols="30" rows="10"></textarea>
                    <!--<span>Type your message</span>-->
                </div>
                <div class="inputBox">
                    <input type="submit" name="" value="Send">
                   
                </div>
            </form>

        </div>
	</div>
</section>
 <!--font awsome-->
 



 {% if message_name %}
<center class="email-received">
   
    <h1> Thanks {{ message_email }}</h1>
    <p>Email recieved,will contact you soon</p>

</center>
{% endif %}












{% endblock %}

templates/detail.html
<h2>product details</h2>


<div class="container">
   
    <div class="row">
        <h2>{{ customer}}</h2>
        {% for product in products %}
        <div class="col-lg-4">
         
        <img class="thumbnail" src="{{ product.image.url }}" alt="">
       
          <div class="box-element product">
            <h6><strong>{{ product.name }}</strong></h6>
            <br>
            <button data-product="{{product.id}}" data-action
            ="add" class="btn btn-outline-secondary add-btn update-cart">Add to cart</button>
            <a href="" class="btn btn-outline-success">view</a>
            <h4 style="display: inline-block; float: right;">
            #{{ product.price|floatformat:2 }}</h4>
          </div>
        </div>
        {% endfor %}
      
      </div>
      </div>

templates/footer.html
<style>
    .footer-dark {
        margin-top: 50px;
  padding:50px 0;
  color:#f0f9ff;
  background-color:#282d32;
  width: 100% !important;
}

.footer-dark h3 {
  margin-top:0;
  margin-bottom:12px;
  font-weight:bold;
  font-size:16px;
}

.footer-dark ul {
  padding:0;
  list-style:none;
  line-height:1.6;
  font-size:14px;
  margin-bottom:0;
}

.footer-dark ul a {
  color:inherit;
  text-decoration:none;
  opacity:0.6;
}

.footer-dark ul a:hover {
  opacity:0.8;
}

@media (max-width:767px) {
  .footer-dark .item:not(.social) {
    text-align:center;
    padding-bottom:20px;
  }
}

.footer-dark .item.text {
  margin-bottom:36px;
}

@media (max-width:767px) {
  .footer-dark .item.text {
    margin-bottom:0;
  }
}

.footer-dark .item.text p {
  opacity:0.6;
  margin-bottom:0;
}

.footer-dark .item.social {
  text-align:center;
}

@media (max-width:991px) {
  .footer-dark .item.social {
    text-align:center;
    margin-top:20px;
  }
}

.footer-dark .item.social > a {
  font-size:20px;
  width:36px;
  height:36px;
  line-height:36px;
  display:inline-block;
  text-align:center;
  border-radius:50%;
  box-shadow:0 0 0 1px rgba(255,255,255,0.4);
  margin:0 8px;
  color:#fff;
  opacity:0.75;
}

.footer-dark .item.social > a:hover {
  opacity:0.9;
}

.footer-dark .copyright {
  text-align:center;
  padding-top:24px;

  font-size:13px;
  margin-bottom:0;
  color: #fff;
}
</style>







  
 
   


<body>
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Address</h3>
                        <ul><li><a href="">I-won-wok Ltd</a></li>
                            <li><a href="#">111 Apapa road</a></li>
                            <li><a href="#">Ebutte metta ,Lagos</a></li>
                           
                        </ul>
                    </div>
                    
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services - All artisans</h3>
                        <ul>
                            <li><a href="#"> Electricians </a></li>
                            <li><a href="#">Plumbers</a></li>
                            <li><a href="#">Carpenters</a></li>
                            <li><a href="#">Mechanics</a></li>
                            <li><a href="#">Tailors</a></li>
                            <li><a href="#">housekeepers</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Phone</h3>
                        <ul>
                            <!--<li><a href="#">+2349160787335</a></li>--
                            <li><a href="#">0807938678</a></li>-->
                            <li><a href="#">+2348177206739 - Whatsapp Only</a></li>
                            <li><a href="#">+2348079385255 </a></li>
                            <li><a href="#">+2347017839642 </a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Email</h3>
                        <ul>
                         
                            <li><a href="#">molisym@me.com</a></li>
                          
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Office Hours</h3>
                        <ul>
                            <li><a href="#"> Mon – Fri | 9:00 – 5:00pm</a></li>
                            <li><a href="#">Sat – Sun | By Appointment</a></li>
                            <li><a href="#">Holidays -</a></li>
                        </ul>
                    </div>
                  
                    <div class="col-sm-6 col-md-3 item" style="margin-top: 30px;">
                        <h3>About Us</h3>
                        <ul>
                            <li><a href="{% url 'products:home' %}">Home</a></li>
                            <li><a href="">Our Team</a></li>
                        
                            <li> <a href="">Property Search</a> </li>
                            <li class="services"><a href="">Our Services</a></li>
                            <li><a href="">Property  Management</a></li>
                            <li><a href="">Marketing</a></li>
                            <li><a href="">Testimonials</a></li>
                            
                            <li><a href="">Contact Us</a></li>
                        </ul>
                    </div>
                   
                    



                    <div class="col item social">
                        <a href="https://m.facebook.com/wilmotinnovationlimited/"><i class="icon ion-social-facebook"></i></a>
                        <a href="#"><i class="icon ion-social-twitter"></i></a>
                        <a href="#"><i class="icon ion-social-snapchat"></i></a>
                        <a href="#"><i class="icon ion-social-instagram"></i></a>
                        <i class="fa-brands fa-facebook-f"></i>
                    </div>
                </div>
                <p class="copyright">I-Wan-wok  © 2022</p>
            </div>
           
        </footer>
        <p class="copyright" style="text-align:left; margin-left:3px" >Devloped by: nuel4xelence@gmail.com</p>
    </div>
    
   

templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'images/brand/title_image2.png' %}" />
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
 

    {% if title %}
<title>{{ title }}</title>
{% else %}

<title>Main Page</title> 
{% endif %}

 


    
<!--jquery library-->

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.slim.min.js" integrity="sha512-6ORWJX/LrnSjBzwefdNUyLCMTIsGoNP6NftMy2UAm1JBm6PRZCO1d7OHBStWpVFZLO+RerTvqX/Z9mBFfCJZ4A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

   <!--animation link-->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>

   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />


   <!--bootstrap link-->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!--google fonts link-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Display:ital,wght@0,100;0,300;0,400;0,500;0,600;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800&family=Oswald:wght@200;300;400&family=Poppins:ital,wght@0,200;0,500;1,200;1,600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&display=swap" rel="stylesheet">

 <!-- link-->
    <link rel="stylesheet" href="{% static 'css/sty.css' %}">
</head>

<body>




<!--top header-->


<header class="head" id="head">
    <div class="container" >
      <div class="row">
       
      <div class="col-md-4 col-12 ms-auto">
        <h2 class="my-md-3 site-title ">I-wan-wok.com</h2>
  
      </div>
      {% if user.is_authenticated %}
      <div class="col-md-4  text-right">
        
        <p class="my-md-4 header-links">
          <a href="{% url 'account:logout' %}" style="font-size: 18px; font-weight: 500;" class="px-2">Logout</a>
     
        </p>
        
      </div>
      <div class="col-md-4 col-12 text-right">
        <p class="my-md-4 header-links">
          <h2  class="welcome">Welcome <strong class="req">&nbsp; {{ request.user }}! </strong> </h2>
        </p>
      </div>
      
    {% else %}
  
      <div class="col-md-4 col-12 text-right">
        <p class="my-md-4 header-links">
          <a href="{% url 'account:login' %}" class="px-2">Login</a>
          <a href="{% url 'account:registration' %}" class="px-1">Create An Account</a>
        </p>
      </div>
    
        {% endif %}
      </div>

     
    </div>
  </header>
<!--end header-->







    <div class="nav">
    
        <input type="checkbox" id="nav-check" class="nav-check" onclick="toggleSelects()">
    
        <div class="nav-btn">
          <label for="nav-check" id="nav-check">
            <span></span>
            <span></span>
            <span></span>
          </label>
        </div>
      
      <div class="navbar-brand" id="">
        <a  href="/"><img class="" src="{%  static 'images/brand/logo3.jpg' %}"  class="img-fluid logo" alt="banner1">
      </a>
        </div>

        <div class="nav-links" id="nav-links">
            <ul>
          <li><a href="{% url 'products:home' %}" target="_blank">Home</a></li>
          <li><a href="{% url 'products:train_staff' %}" target="_blank">Train your staff</a></li>
          <li><a href="{% url 'products:jobs' %}" target="_blank">Our Services</a></li>
          <li><a href="{% url 'artisan:artisanReg' %}" target="_blank">Become A worker</a></li>
         <!-- <li><a href="{% url 'products:contact' %}" target="_blank">partnership</a></li>-->
          <li><a href="{% url 'products:post_service' %}" target="_blank">Post A Job</a></li>
           
          {% if user.artisan %}
        
          <li><a style="color: #dc3545;" href="{% url 'account:artisanPage' %}">Dashboard</a>

           </li>
            {% elif user.details %}

            <li><a  href="{% url 'account:dashboard' %}">Dashboard</a>
           
                <div style="color: red;" >{{ request.user }}</div></li>

            {% endif %}    
         
          <li ><a  href="{% url 'products:contact' %}">Contact us</a></li>
          <li><a  href="{% url 'products:terms' %}">T&C</a>
          </li>
          <li ><a  href="">Jobs</a></li>
            </ul>
            
        </div>
      </div>


      
  



















<div class="all-content" id="content">
{% block content %}
{% endblock %}
</div>



{% include 'footer.html' %}








 




    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

 
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>


<script src="{% static 'js/carousels.js' %}"></script>

<script src="{% static 'js/sty.js' %}"></script>

  
</body>

</html>

templates/search.html
{% extends 'main.html' %}
{% load static %}  
{% block content %} 

<div class="container">
{% for product in item %}
<div class="card" style="width: 25rem; margin-top: 60px;">
    <img class="card-img-top" src="{{ products.img.url }}" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">{{ product.name }}</h5>
      <p class="card-text">{{product.desc}}</p>
      <a href="{% url 'products:product_dest' product.pk %}" class="btn btn-danger">Request the service</a>
    </div>
  </div>
{% endfor %}
</div>
  {% endblock %}