account/urls.py
from django.urls import path
from .views import *
from .import views

from django.contrib.auth import views as auth_views



app_name = 'account'


urlpatterns = [

    path('registration/',views.registration,name ='registration'),
    path('register/',views.registerPage,name ='register'),
   
    path('login/' ,views.loginPage , name='login'),
    path('admin_page/',views.adminPage ,name='admin_page'),
    path('update_info/', views.update_info, name="update_info"),
   
    path('logout/', views.logoutPage, name='logout'),
  
    path('client_register/',views.clientRegister,name ='client_register'),
    path('dashboard/',views.clientDashboard,name ='dashboard'),
  
    path('artisanPage/',views.artisanDashboard,name ='artisanPage'),
    
    
  

    
]

artisan/urls.py
from os import name
from django.urls import path
from .views import *
from .import views

from django.contrib.auth import views as auth_views



app_name = 'artisan'


urlpatterns = [
     path('artisanReg/', views.artisanRegistration, name='artisanReg'),
     path('confirmed_orders/', views.confirmedOrders, name='confirmed_orders'),
     path('artisan_update/', views.artisan_update, name="artisan_update"),

     path('paidJobs',views.paidJobs, name='paidJobs'),
     
     path('job_detail/<int:id>/',views.jobDetail, name='job_detail'),
     path('services_completed/',views.artisan_services, name='services_completed'),
     path('current_job/', views.currentJob, name='current_job'),
     path('accepted/<int:id>/', views.jobAccepted, name='accepted'),
     path('current_job_info/', views.CurrentJobInfo, name='current_job_info'),

     path('completed/<int:id>/', views.completeJob, name='completed'),
     path('congratulation/', views.congratulations, name='congratulation'),

      path("artisan-search/", SearchFlipView.as_view(), name="artisan-search"),
      path("outstanding/", views.outstandingPay, name="outstanding"),
     path("listJob/", views.JobList, name="listJob"),

      path('searchArtisans/<int:pk>/',views.artisanList,name="searchArtisans"),
      path("artisan_request/<int:pk>/", views.artisanRequest, name="artisan_request"),

       path("bank/", views.bankDetails, name="bank"),
     path("bank_update/", views.update_bank_info, name="bank_update"),
    



   
]

iwan_work/urls.py
from django.contrib import admin

from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' ,include('products.urls')),
    path('account/', include('account.urls')),
   
    path('artisan/' ,include('artisan.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import *
from .import views

app_name = 'products'


urlpatterns = [
    

    path('', views.home, name='home'),
    path('update_order/<int:pk>/',views.updateOrder,name='update_order'),
    path('detail/<int:id>/', views.details, name='detail'),
     path('jobs/' , AvailableJobs.as_view() ,name="jobs"),
    path('terms/',views.terms_and_conditions, name="terms"),
    
    path('product_dest/<pk>', views.product_dest, name='product_dest'),
    path('orderlist/', views.orderlist, name='orderlist'),
    path('add_to_cart/<pk>', views.add_to_cart, name='add_to_cart'),
    path('orderlist/', views.orderlist, name='orderlist'),
    path('add_item/<int:pk>', views.add_to_cart, name='add_item'),
    path('remove_item/<int:pk>', views.delete_order, name='remove_item'),

    path('search/', views.search , name='search'),
    path('contact/',views.contact ,name='contact'),
    
    path('payment/', views.payment, name='payment'),
     path('handle_confirmation/', views.handle, name='handle_confirmation'),
     path("post_service/", views.postServiceNeeded, name="post_service"),


    path('new/', views.newMethod, name='new'),
    path('add_service_item/<int:pk>', views.serviceRequestCart, name='add_service_item'), 
    path('servicelist/', views.Servicelist, name='servicelist'),
    path('service_payment/', views.servicePayment, name='service_payment'),

    path('payment_confirmation/', views.paymentConfirmation, name='payment_confirmation'),

    path("post_job/", views.PostJobItem, name="post_job"),

     path('service_list/', views.Servicelisting, name='service_list'),

    path('train_staff/', views.StaffTraining, name='train_staff'),
    
    path("workers_detail/", views.artisanDetail, name="workers_detail"),
    path("all_services/", views.serviceCompeleted, name="all_services"),
]

artisan/views.py
from django.utils import timezone
from django.shortcuts import render,redirect

from django.http import Http404
from django.contrib import messages

from django.contrib.auth.decorators import login_required

from products .models import *
from django.db.models import Q 

from django.views.generic.base import TemplateView
from django.views.generic import (
    ListView ,DetailView,
)
from account.models import *
from .forms import *


# Create your views here.

#artisan registration
def artisanRegistration(request):
    if request.method == 'POST':
        #input taking-basic and detailed information
        form1 = CreateUserForm(request.POST)
        form4 = WorkersForm(request.POST,request.FILES) 
        
        #check both basic and detailed data to verify the validity
        if form1.is_valid() and form4.is_valid():
            user = form1.save()
            profile = form4.save(commit=False)
            
            #associate detailed data to basic data of the user
            profile.user =user
            profile.save()
            img_obj = form4.instance
            id = form1.cleaned_data.get('id')
            messages.success(request, 'Account was created for ' , id)

            return redirect('account:login')
    #empty forms
    else:
        form1 =CreateUserForm()
        form4 = WorkersForm()
        
    context = {'form1':form1, 'form4': form4}   
    return render(request, 'account/artisan_register.html', context)



def confirmedOrders(request):
    return render(request ,'artisans/available_jobs.html')  


#updating artisan's data
@login_required
def artisan_update(request):
    if request.method =="POST":
        #taking data from the user
        form1 = UserUpdateForm(request.POST, instance = request.user)
        form4 = ArtisanUpdateForm(request.POST, request.FILES,instance = request.user.artisan)
        
        #check forms validity
        if form1.is_valid() and form4.is_valid():
            form1.save()
            form4.save()

            messages.success(request,"Successfully updated")
            return redirect('account:artisanPage')
               
        else:
            messages.warning(request,"Not updated")
    
    # empty form
    else:
        form1 = UserUpdateForm(instance = request.user)
        form4 = ArtisanUpdateForm(instance=request.user.artisan)          

    context = {'form1':form1, 'form4':form4}

    return render(request,'account/update_artisan_info.html',context)  



@login_required
def paidJobs(request):

    if ServiceRequest.objects.filter(ordered=True,status='Paid').exists():
        res=ServiceRequest.objects.filter(ordered=True,status='Paid')
        context ={'areaJobs':res}
        return render(request,'check.html',context) 
    else:
        messages.success(request, f"No {res} work available now.Please check back later.") 
        return render(request,'check.html') 
    


@login_required
def paidJobssssssss(request):
    #the artisan
    artisan = Artisan.objects.filter(user=request.user)
   
    job_location = request.user.artisan.location
    #job type
    job_name   = request.user.artisan.profession_name

    #artisan job -first on the list
    if ServiceRequest.objects.filter(ordered=True,status='Paid',artisan=artisan[0]).exists():
        res=ServiceRequest.objects.filter(ordered=True,status='Paid',artisan=artisan[0])
        
        #jobs accepted by the artisan
        if ServiceRequest.objects.filter(ordered=True,status='Paid',artisan=artisan[0],accepted='Accepted').exists():
            messages.info(request ,"No new jobs avaialable now.")
            return render(request,'check.html')
            
        context ={'areaJobs':res}
        return render(request,'check.html',context) 

    #if artisan has no job available
    elif ServiceRequest.objects.filter(ordered=True,status='Paid',product=job_name).exists():        
        res =ServiceRequest.objects.filter(ordered=True,status='Paid',product=job_name)

        context ={'areaJobs':res}
        return render(request,'check.html',context) 
    
    else:
        messages.success(request, f"No {job_name} work available now.Please check back later.") 
        return render(request,'check.html')  


#job detail
@login_required
def jobDetail(request,id):
    job_info= ServiceRequest.objects.get(id =id)
    context = {'job_info': job_info }
    return render(request,'products/job_detail.html',context)



#job detail
@login_required
def jobDetailsssss(request,id):
    #authenticate the user
    if request.user.is_authenticated:
        artisan = [Artisan.objects.filter(user=request.user)]
        
        #request id
        job_info= ServiceRequest.objects.filter(id =id)
        for job in job_info:
            pn =job.id
            
            #creating viwedjob object
            job_detail,create =ViewedJob.objects.get_or_create(user=request.user,
            job_name=job.product.name,category=job.product.category,
            description =job.description,price =job.get_service_rate(),client=job.user.last_name,address =job.address,
            date=job.date_created,phone=job.user.details.phone,job_order_id=job.id
        )
  
    context = {'job_info': job_info,'pt':pn }
    return render(request,'products/job_detail.html',context)



#artisan accepted jobs
@login_required  
def jobAccepted(request,id):
    artisan = [Artisan.objects.get(user=request.user)]

    #if service ordered is paid,get the job id and assign the artisan to it
    if ServiceRequest.objects.get(id=id, ordered=True,status='Paid'):
        accepted_job= ServiceRequest.objects.filter(id=id, ordered=True,status='Paid')

        for b in accepted_job:
            b.artisan =Artisan.objects.get(user=request.user)
            b.save()

        #update the service order to being accepted 
        ServiceRequest.objects.filter(id=id, ordered=True,status='Paid').update(accepted ="Accepted" ,
        accepted_date =timezone.now())
     
    #get job viwed by the artisan,add date to it
    if ViewedJob.objects.filter(user=request.user,job_order_id=id).exists():
        current_job = ViewedJob.objects.filter(user=request.user,job_order_id=id)
        ViewedJob.objects.filter(user=request.user,job_order_id=id).update(accepted ="Accepted" ,
        accepted_date =timezone.now())

        return redirect('account:artisanPage')
        
    return redirect('/')
                       
                    


@login_required
def currentJob(request):
    user=request.user  
   
   #on going job
    if not ViewedJob.objects.filter(user=user,accepted='Accepted').exists():
            messages.info(request,'You dont have any on going job yet!Go to dashboard and select a job to do')
            return render(request,'artisans/no_service_rendered.html')

    #if accepted,get the last one
    if ViewedJob.objects.filter(user=user,accepted='Accepted').exists():
        current_job = ViewedJob.objects.filter(user=user,accepted='Accepted').last()
        if current_job.work_done == True:
            messages.info(request,'This job is concluded already')

        context ={'current_job':current_job}
    return render(request,'artisans/current_job.html',context)



#view current job
@login_required
def CurrentJobInfo(request):
    user = request.user
    #if artisan has not accepted ,he no current
    if not ViewedJob.objects.filter(user=user,accepted='Accepted').exists():
            messages.info(request,'You dont have any job to confirm here!Go to dashboard and select a job to do')
            return render(request,'artisans/no_service_rendered.html')

    # accepted jobs
    elif ViewedJob.objects.filter(user=user,accepted='Accepted').exists():
        try:
            jobinfo = ViewedJob.objects.filter(user=user,accepted='Accepted').last()
            if jobinfo.work_done == True:
                messages.info(request,'Job already registered for payment')
                return render(request,'payments/payment_underway.html')

                
        except:
            raise Http404
        return render(request, 'artisans/currentjobinfo.html', {'jobinfo':jobinfo})

    


#job completed
@login_required
def completeJob(request,id):
    user = request.user
    #artisan user
    artisan = Artisan.objects.get(user=request.user)
     
    #all work done jobs
    if ViewedJob.objects.filter(user=user,accepted='Accepted',job_order_id=id,work_done=True).exists():
        messages.info(request,'Job already registered for payment. Pick up another job today.')
        return render(request,'artisans/no_service_rendered.html')

    #work accepted nut not completed yet
    elif ViewedJob.objects.filter(user=user,accepted='Accepted',job_order_id=id):

        if ServiceRequest.objects.filter(id=id,artisan =artisan, ordered=True,status='Paid',accepted ="Accepted"):
            ViewedJob.objects.filter(user=user,accepted='Accepted',job_order_id=id).update(work_done=True)
            ServiceRequest.objects.filter(artisan=artisan, ordered=True,status='Paid',accepted ="Accepted",id=id).update(work_done=True)

            return redirect('artisan:congratulation')

        else:
            messages.info(request,'Service Item not found')
            return render(request,'artisans/no_service_rendered.html')
    else:
        messages.info(request,'Service not accepted yet.Contact the admin')  
        return render(request,'artisans/no_service_rendered.html')      

           
#conformation of registration        
def congratulations(request):
    messages.info(request,'Congratulations! Your payment is under processing') 
    return render(request,'artisans/congrats.html')

  
#artisan servies 
def artisan_services(request):
    user = Artisan.objects.get(user=request.user)
    # if artisan has no job done 
    if not ServiceRequest.objects.filter(artisan=user,accepted='Accepted',work_done=True).exists():
        messages.info(request,'You dont have any recorded service yet.Go to Jobs in your neigborhood and select a job')

templates/dashboard/artisan/artisan_info_dashboard.html
{% load static %}


<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>I_client_dashboard</title>
  <!-- base:css -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'template/css/vertical-layout-light/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static 'images/brand/title_image2.png' %}" />
  <!--<link rel="shortcut icon" href="{% static 'template/images/favicon.png' %}" />-->
  <link rel="stylesheet" href="/static/template/css/vertical-layout-light/styling.css">
</head>
<body>

  <style>
    .user_image{
      height: 150px;
      width: 150px;
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      text-align: center;
      padding: 10px 20px;
      border-radius: 50%;
    }
    li {
   list-style: none !important;
  }
  a{
    text-decoration: none;
  }
  .collapse li a{
    color: #000 !important;
  }
.brand-logo{
  display: block;
}
@media screen and (max-width: 950px){
    .navbar-toggler{
      display: block !important;
    }
    #ui-basic{
    display: block !important;
   }

   @media screen and (max-width: 991px){
   .sidebar-offcanvas {
  
}
   }

 
  }
  </style>
 

    <!-- partial:partials/_navbar.html -->
  <div class="container-scroller">
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="navbar-brand-wrapper d-flex justify-content-center">
        <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
          <a class="navbar-brand brand-logo" href=""><img src="/static/images/brand2.jpg" alt="logo"/></a>
          <!--<a class="navbar-brand brand-logo-mini" href=""><img src="/static/images/brand4.jpg" alt="logo"/></a>-->
          <button class="navbar-toggler navbar-toggler align-self-center" id="navbar-toggler" type="button" data-toggle="minimize">
            <span class="typcn typcn-th-menu"></span>
          </button>
        </div>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <ul class="navbar-nav mr-lg-2">
         
          <li class="nav-item nav-date dropdown">
            <a class="nav-link d-flex justify-content-center align-items-center" href="{% url 'account:logout' %}">
              <h6 class="date mb-0"><b>Home Page</b></h6>
              <!--<i class="typcn typcn-calendar"></i>-->
            </a>
         
        </ul>
        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item nav-date dropdown">
            <a class="nav-link d-flex justify-content-center align-items-center" href="{% url 'account:logout' %}">
              <h6 class="date mb-0"><b>logouts</b></h6>
              <!--<i class="typcn typcn-calendar"></i>-->
            </a>
          </li>
         
        </ul>
        <!--<button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="typcn typcn-th-menu"></span>
        </button>-->
      </div>
    </nav>
    <!-- partial -->
    <nav class="navbar-breadcrumb col-xl-12 col-12 d-flex flex-row p-0">
      <div class="navbar-links-wrapper d-flex align-items-stretch">
        <div class="nav-link">
          <a href="{% url 'products:jobs' %}"><b>Services</b></a>
        </div>
        <div class="nav-link">
          <a href="{% url 'products:contact' %}"><b>ContactUs</b></a>
          <!--<a href="javascript:;"><i class="typcn typcn-mail"></i></a>-->
        </div>
        <div class="nav-link">
          <a href="{% url 'products:terms' %}"><b>T&C</b></a>
        </div>
        <!--<div class="nav-link">
          <a href="javascript:;"><i class="typcn typcn-document-text"></i></a>
        </div>-->
      </div>
      
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <ul class="navbar-nav mr-lg-2">
          <li class="nav-item ml-0">
            <h4 class="mb-0">Welcome,{{ request.user.last_name}}</h4>
          </li>
          
        </ul>
        
      </div>
    </nav>
    <div class="container-fluid page-body-wrapper">
   
      <div class="theme-setting-wrapper">
        <div id="settings-trigger"><i class="typcn typcn-cog-outline"></i></div>
        <div id="theme-settings" class="settings-panel">
          <i class="settings-close typcn typcn-times"></i>
          <p class="settings-heading">SIDEBAR SKINS</p>
          <div class="sidebar-bg-options selected" id="sidebar-light-theme"><div class="img-ss rounded-circle bg-light border mr-3"></div>Light</div>
          <div class="sidebar-bg-options" id="sidebar-dark-theme"><div class="img-ss rounded-circle bg-dark border mr-3"></div>Dark</div>
          <p class="settings-heading mt-2">HEADER SKINS</p>
          <div class="color-tiles mx-0 px-4">
            <div class="tiles success"></div>
            <div class="tiles warning"></div>
            <div class="tiles danger"></div>
            <div class="tiles info"></div>
            <div class="tiles dark"></div>
            <div class="tiles default"></div>
          </div>
        </div>
      </div>
      
      <!-- partial -->
      <!-- partial:partials/_sidebar.html -->
      <nav class="sidebar " id="sidebar">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="typcn typcn-device-desktop menu-icon"></i>
              <span class="menu-title">Dashboard</span>
              <div class="badge badge-danger">new</div>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
              <i class="typcn typcn-document-text menu-icon"></i>
              <span class="menu-title"><b>Jobs Info</b></span>
              <i class="menu-arrow"></i>
            </a>
   

            <div class="collapse" id="ui-basic">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link btn btn-light " href="{% url 'artisan:paidJobs' %}"><b>Available Jobs</b></a></li>
                <li class="nav-item"> <a class="nav-link btn btn-light" href="{% url 'artisan:current_job' %}" ><b>Your current job</b></a></li>
                <li class="nav-item"> <a class="nav-link btn btn-light" href="{% url 'artisan:current_job_info' %}"><b>Register job for payment</b></a></li>
                <li class="nav-item"> <a class="nav-link btn btn-light" href="{% url 'artisan:services_completed' %}"><b>Previous Jobs</b></a></li>
                <!--<li class="nav-item"> <a class="nav-link btn btn-light" href=""><b>Bank Info</b></a></li>-->
                <li class="nav-item"> <a class="nav-link btn btn-light" href="{% url 'artisan:bank' %}"><b>Bank Info</b></a></li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#form-elements" aria-expanded="false" aria-controls="form-elements">
              <i class="typcn typcn-film menu-icon"></i>
              <span class="menu-title"><b>Account Setting</b></span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="form-elements">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"><a class="nav-link  btn-danger" href="{% url 'artisan:artisan_update' %}"><b>Edit Information</b></a></li>
              </ul>
            </div>
            <div class="collapse" id="form-elements">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"><a class="nav-link  btn-danger" href="{% url 'artisan:artisan_update' %}"><b>Edi Bank Information</b></a></li>
              </ul>
            </div>
          </li>
         
        </ul>
      </nav>

      
      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">


          <!--start-->
     
          <div class="row">
            <div class="col-xl-4 grid-margin stretch-card">
              <div class="card">
                <div class="card-body border-bottom">
                  <div class="d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-2 mb-md-0 text-uppercase font-weight-medium">Bio</h6>
                   
                      <img src="{{ user.artisan.profile_img.url }}" class="user_image" alt="not ready ">
                   
                    
                  </div>
                </div>
                
                <div class="row">
                  {% for message in messages %}
                     <p id="messages" style="text-align: center; font-size:18px">Hello  {{user.last_name}}, {{ message }}</p>
                  {% endfor %}
                  </div>
                <div class="card-body">
                  <div class="card card-body">
                    <h5>Contact Information</h5>
                    <hr>
                    <p>username: {{user.username}}</p>
                    <p>Full name: {{user.first_name}} &nbsp; {{user.last_name}}</p>
                    <p>Phone: {{user.artisan.phone}}</p>
                    <p>NIN: {{user.artisan.nin}}</p>
                   
                    <p>Email: {{user.email}}</p>
                    <p>Address: {{user.artisan.address}}</p>
                  </div>

               
                   
                </div>
              </div>
            </div>
          
          </div>

   
         
        
            <div class="col-md-4 col-xl-4 grid-margin stretch-card" id="stats">
              <div class="card">
                <div class="card-body border-bottom">
                  <div class="d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-2 mb-md-0 text-uppercase font-weight-medium">Available jobs</h6>
                  </div>
                    <div class="col-md-7" style="align-items: center;">
                       <hr>
                            <div class="card card-body">
                            <table class="table table-sm" >
                            <tr style="margin-top: 70px;"> 

                            {% for item in areaJobs %}

                            <h3 style="text-transform: capitalize;">{{item.product.name}} &nbsp;<a href="{% url 'artisan:job_detail' item.id %}" style="align-items: center; text-transform: capitalize;" name="view-detail" class="btn btn-success right">See Detail</a>
                            </h3>

                            <hr>
                            {% endfor %}
                            </tr>
                            </table>
                            </div>
                          </div>
                </div>

                <div class="card-body">
                  <canvas id="sales-chart-d" height="320"></canvas>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex align-items-center justify-content-between justify-content-md-center justify-content-xl-between flex-wrap mb-4">
                    <div>
                      <p class="mb-2 text-md-center text-lg-left">Amount Payable</p>
                      <h1 class="mb-0">8742</h1>
                    </div>
                    <i class="typcn typcn-briefcase icon-xl text-secondary"></i>
                  </div>
                  <canvas id="expense-chart" height="80"></canvas>
                </div>
              </div>
            </div>
            <div class="col-md-4 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex align-items-center justify-content-between justify-content-md-center justify-content-xl-between flex-wrap mb-4">
                    <div>
                      <p class="mb-2 text-md-center text-lg-left">Total Budget</p>
                      <h1 class="mb-0">47,840</h1>
                    </div>
                    <i class="typcn typcn-chart-pie icon-xl text-secondary"></i>
                  </div>
                  <canvas id="budget-chart" height="80"></canvas>
                </div>
              </div>
            </div>
            <div class="col-md-4 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex align-items-center justify-content-between justify-content-md-center justify-content-xl-between flex-wrap mb-4">
                    <div>
                      <p class="mb-2 text-md-center text-lg-left">Total Balance</p>
                      <h1 class="mb-0">$7,243</h1>
                    </div>
                    <i class="typcn typcn-clipboard icon-xl text-secondary"></i>
                  </div>
                  <canvas id="balance-chart" height="80"></canvas>
                </div>
              </div>
            </div>
          </div>

         
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
      
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>


  <!-- container-scroller -->
{% include 'footer.html' %}
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="{% static 'template/js/dashboard.js ' %}"></script>
  <!-- End custom js for this page-->
</body>

</html>

templates/dashboard/artisan/available_jobs.html
{% extends 'main.html' %}
{% block content %}

<style>
    .main-panel {
  transition: width 0.25s ease, margin 0.25s ease;
  width: calc(100% - 236px);
  min-height: calc(100vh - 4.625rem);
  display: -webkit-flex;
  display: flex;
  -webkit-flex-direction: column;
  flex-direction: column;
}
.row {
  display: flex;
  flex-wrap: wrap;
  margin-right: -0.6875rem;
  margin-left: -0.6875rem;
}
.content-wrapper {
  padding: 0 1.812rem 1.812rem;
  width: 100%;
  -webkit-flex-grow: 1;
  flex-grow: 1;
}

@media (max-width: 767px) {
  .content-wrapper {
    padding: 1.5rem 1.5rem;
  }
}
</style>
 <div class="main-panel">
    <div class="content-wrapper">

<div class="col-md-12 col-xl-4 grid-margin stretch-card" id="stats">
    <div class="card">
      <div class="card-body border-bottom">
        <div class="d-flex justify-content-between align-items-center flex-wrap">
          <h6 class="mb-2 mb-md-0 text-uppercase font-weight-medium">Available jobs</h6>
        </div>
          <div class="col-md-7" style="align-items: center;">
             <hr>
                  <div class="card card-body">
                  <table class="table table-sm" >
                  <tr style="margin-top: 70px;"> 

                  {% for item in areaJobs %}

                  <h3 style="text-transform: capitalize;">{{item.product.name}} &nbsp;<a href="{% url 'artisan:job_detail' item.id %}" style="align-items: center; text-transform: capitalize;" name="view-detail" class="btn btn-success right">See Detail</a>
                  </h3>

                  <hr>
                  {% endfor %}
                  </tr>
                  </table>
                  </div>
                </div>
      </div>

      <div class="card-body">
        <canvas id="sales-chart-d" height="320"></canvas>
      </div>
    </div>
  </div>
</div>
</div>

{% endblock %}